version: "3.5"
services:
  mqtt:
    build: ./mqtt/
    restart: on-failure
    ports:
      - "1883:1883"
      - "9001:9001"
    expose:
      - 1883
    volumes:
      - ./mqtt/mosquitto/data:/mosquitto/data
      - ./mqtt/mosquitto/config:/mosquitto/config
      - ./mqtt/mosquitto/log:/mosquitto/log
    networks: 
      - network_test_bed

  mongo:
    image: mongo:4.2.3-bionic
    container_name: mongo
    restart: always
    volumes:
      - ./mongodb/data:/data/db
      - ./mongodb/mongo.conf:/etc/mongod.conf
      - ./mongodb/mongod.log:/var/log/mongodb/mongod.log
    ports:
      - '27017:27017'
    expose:
      - 27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin
    environment:
      - PYTHONUNBUFFERED=1
      - MONGO_INITDB_DATABASE=admin
    networks: 
      - network_test_bed
    command: 
      - '--quiet'
      - '--config'
      - '/etc/mongod.conf'
      - '--logpath'
      - '/var/log/mongodb/mongod.log'
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:27017"]
        interval: 30s
        timeout: 10s
        retries: 5

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    restart: always
    environment:
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      WAIT_HOSTS: mongo:27017
    environment:
      - PYTHONUNBUFFERED=1
    networks: 
      - network_test_bed
    depends_on: 
      - "mongo"
    links:
      - "mongo"

  broker:
    build: ./broker/
    restart: on-failure
    ports:
      - "7000:7000"
    expose:
      - 7000
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./broker:/usr/src/app:z
      - ./common/:/usr/src/app/common:z
    depends_on: 
      - mongo
      - mqtt
    networks: 
      - network_test_bed

  rsu-0001:
    build: ./rsu/
    restart: on-failure #on-failure
    volumes:
      - ./rsu:/usr/src/app:z
      - ./common/:/usr/src/app/common:z
    environment:
      - PYTHONUNBUFFERED=1
      - RSU_ID=0001
    depends_on: 
      - mqtt
    networks: 
      - network_test_bed

networks:
  network_test_bed: