version: "3.5"
services:
  broker:
    build: ./broker/
    restart: on-failure
    ports:
      - "7000:7000"
    expose:
      - 7000
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./broker:/usr/src/app:z
      - ./common/:/usr/src/app/common:z
    networks: 
      - network_test_bed

  rsu-0000:
    image: linusmotu/rsu-base:1.0
    restart: on-failure
    volumes:
      - ./rsu:/usr/src/app:z
      - ./common/:/usr/src/app/common:z
    environment:
      - PYTHONUNBUFFERED=1
      - RSU_ID=0000
    networks: 
      - network_test_bed
    command: 
      - 'python3'
      - '-u'
      - '/usr/src/app/rsu.py'

  rsu-0001:
    image: linusmotu/rsu-base:1.0
    restart: on-failure
    volumes:
      - ./rsu:/usr/src/app:z
      - ./common/:/usr/src/app/common:z
    environment:
      - PYTHONUNBUFFERED=1
      - RSU_ID=0001
    networks: 
      - network_test_bed
    command: 
      - 'python3'
      - '-u'
      - '/usr/src/app/rsu.py'

  rsu-0002:
    image: linusmotu/rsu-base:1.0
    restart: on-failure
    volumes:
      - ./rsu:/usr/src/app:z
      - ./common/:/usr/src/app/common:z
    environment:
      - PYTHONUNBUFFERED=1
      - RSU_ID=0002
    networks: 
      - network_test_bed
    command: 
      - 'python3'
      - '-u'
      - '/usr/src/app/rsu.py'

  rsu-0003:
    image: linusmotu/rsu-base:1.0
    restart: on-failure
    volumes:
      - ./rsu:/usr/src/app:z
      - ./common/:/usr/src/app/common:z
    environment:
      - PYTHONUNBUFFERED=1
      - RSU_ID=0003
    networks: 
      - network_test_bed
    command: 
      - 'python3'
      - '-u'
      - '/usr/src/app/rsu.py'

  rsu-0004:
    image: linusmotu/rsu-base:1.0
    restart: on-failure
    volumes:
      - ./rsu:/usr/src/app:z
      - ./common/:/usr/src/app/common:z
    environment:
      - PYTHONUNBUFFERED=1
      - RSU_ID=0004
    networks: 
      - network_test_bed
    command: 
      - 'python3'
      - '-u'
      - '/usr/src/app/rsu.py'

  rsu-0005:
    image: linusmotu/rsu-base:1.0
    restart: on-failure
    volumes:
      - ./rsu:/usr/src/app:z
      - ./common/:/usr/src/app/common:z
    environment:
      - PYTHONUNBUFFERED=1
      - RSU_ID=0005
    networks: 
      - network_test_bed
    command: 
      - 'python3'
      - '-u'
      - '/usr/src/app/rsu.py'

  rsu-0006:
    image: linusmotu/rsu-base:1.0
    restart: on-failure
    volumes:
      - ./rsu:/usr/src/app:z
      - ./common/:/usr/src/app/common:z
    environment:
      - PYTHONUNBUFFERED=1
      - RSU_ID=0006
    networks: 
      - network_test_bed
    command: 
      - 'python3'
      - '-u'
      - '/usr/src/app/rsu.py'

  rsu-0007:
    image: linusmotu/rsu-base:1.0
    restart: on-failure
    volumes:
      - ./rsu:/usr/src/app:z
      - ./common/:/usr/src/app/common:z
    environment:
      - PYTHONUNBUFFERED=1
      - RSU_ID=0007
    networks: 
      - network_test_bed
    command: 
      - 'python3'
      - '-u'
      - '/usr/src/app/rsu.py'

  rsu-0008:
    image: linusmotu/rsu-base:1.0
    restart: on-failure
    volumes:
      - ./rsu:/usr/src/app:z
      - ./common/:/usr/src/app/common:z
    environment:
      - PYTHONUNBUFFERED=1
      - RSU_ID=0008
    networks: 
      - network_test_bed
    command: 
      - 'python3'
      - '-u'
      - '/usr/src/app/rsu.py'

  rsu-0009:
    image: linusmotu/rsu-base:1.0
    restart: on-failure
    volumes:
      - ./rsu:/usr/src/app:z
      - ./common/:/usr/src/app/common:z
    environment:
      - PYTHONUNBUFFERED=1
      - RSU_ID=0009
    networks: 
      - network_test_bed
    command: 
      - 'python3'
      - '-u'
      - '/usr/src/app/rsu.py'

  rsu-0010:
    image: linusmotu/rsu-base:1.0
    restart: on-failure
    volumes:
      - ./rsu:/usr/src/app:z
      - ./common/:/usr/src/app/common:z
    environment:
      - PYTHONUNBUFFERED=1
      - RSU_ID=0010
    networks: 
      - network_test_bed
    command: 
      - 'python3'
      - '-u'
      - '/usr/src/app/rsu.py'

  rsu-0011:
    image: linusmotu/rsu-base:1.0
    restart: on-failure
    volumes:
      - ./rsu:/usr/src/app:z
      - ./common/:/usr/src/app/common:z
    environment:
      - PYTHONUNBUFFERED=1
      - RSU_ID=0011
    networks: 
      - network_test_bed
    command: 
      - 'python3'
      - '-u'
      - '/usr/src/app/rsu.py'

  rsu-0012:
    image: linusmotu/rsu-base:1.0
    restart: on-failure
    volumes:
      - ./rsu:/usr/src/app:z
      - ./common/:/usr/src/app/common:z
    environment:
      - PYTHONUNBUFFERED=1
      - RSU_ID=0012
    networks: 
      - network_test_bed
    command: 
      - 'python3'
      - '-u'
      - '/usr/src/app/rsu.py'

  rsu-0013:
    image: linusmotu/rsu-base:1.0
    restart: on-failure
    volumes:
      - ./rsu:/usr/src/app:z
      - ./common/:/usr/src/app/common:z
    environment:
      - PYTHONUNBUFFERED=1
      - RSU_ID=0013
    networks: 
      - network_test_bed
    command: 
      - 'python3'
      - '-u'
      - '/usr/src/app/rsu.py'

  rsu-0014:
    image: linusmotu/rsu-base:1.0
    restart: on-failure
    volumes:
      - ./rsu:/usr/src/app:z
      - ./common/:/usr/src/app/common:z
    environment:
      - PYTHONUNBUFFERED=1
      - RSU_ID=0014
    networks: 
      - network_test_bed
    command: 
      - 'python3'
      - '-u'
      - '/usr/src/app/rsu.py'

  rsu-0015:
    image: linusmotu/rsu-base:1.0
    restart: on-failure
    volumes:
      - ./rsu:/usr/src/app:z
      - ./common/:/usr/src/app/common:z
    environment:
      - PYTHONUNBUFFERED=1
      - RSU_ID=0015
    networks: 
      - network_test_bed
    command: 
      - 'python3'
      - '-u'
      - '/usr/src/app/rsu.py'

  rsu-0016:
    image: linusmotu/rsu-base:1.0
    restart: on-failure
    volumes:
      - ./rsu:/usr/src/app:z
      - ./common/:/usr/src/app/common:z
    environment:
      - PYTHONUNBUFFERED=1
      - RSU_ID=0016
    networks: 
      - network_test_bed
    command: 
      - 'python3'
      - '-u'
      - '/usr/src/app/rsu.py'

  rsu-0017:
    image: linusmotu/rsu-base:1.0
    restart: on-failure
    volumes:
      - ./rsu:/usr/src/app:z
      - ./common/:/usr/src/app/common:z
    environment:
      - PYTHONUNBUFFERED=1
      - RSU_ID=0017
    networks: 
      - network_test_bed
    command: 
      - 'python3'
      - '-u'
      - '/usr/src/app/rsu.py'

  rsu-0018:
    image: linusmotu/rsu-base:1.0
    restart: on-failure
    volumes:
      - ./rsu:/usr/src/app:z
      - ./common/:/usr/src/app/common:z
    environment:
      - PYTHONUNBUFFERED=1
      - RSU_ID=0018
    networks: 
      - network_test_bed
    command: 
      - 'python3'
      - '-u'
      - '/usr/src/app/rsu.py'

  rsu-0019:
    image: linusmotu/rsu-base:1.0
    restart: on-failure
    volumes:
      - ./rsu:/usr/src/app:z
      - ./common/:/usr/src/app/common:z
    environment:
      - PYTHONUNBUFFERED=1
      - RSU_ID=0019
    networks: 
      - network_test_bed
    command: 
      - 'python3'
      - '-u'
      - '/usr/src/app/rsu.py'

  rsu-0020:
    image: linusmotu/rsu-base:1.0
    restart: on-failure
    volumes:
      - ./rsu:/usr/src/app:z
      - ./common/:/usr/src/app/common:z
    environment:
      - PYTHONUNBUFFERED=1
      - RSU_ID=0020
    networks: 
      - network_test_bed
    command: 
      - 'python3'
      - '-u'
      - '/usr/src/app/rsu.py'

  rsu-0021:
    image: linusmotu/rsu-base:1.0
    restart: on-failure
    volumes:
      - ./rsu:/usr/src/app:z
      - ./common/:/usr/src/app/common:z
    environment:
      - PYTHONUNBUFFERED=1
      - RSU_ID=0021
    networks: 
      - network_test_bed
    command: 
      - 'python3'
      - '-u'
      - '/usr/src/app/rsu.py'

  rsu-0022:
    image: linusmotu/rsu-base:1.0
    restart: on-failure
    volumes:
      - ./rsu:/usr/src/app:z
      - ./common/:/usr/src/app/common:z
    environment:
      - PYTHONUNBUFFERED=1
      - RSU_ID=0022
    networks: 
      - network_test_bed
    command: 
      - 'python3'
      - '-u'
      - '/usr/src/app/rsu.py'

  rsu-0023:
    image: linusmotu/rsu-base:1.0
    restart: on-failure
    volumes:
      - ./rsu:/usr/src/app:z
      - ./common/:/usr/src/app/common:z
    environment:
      - PYTHONUNBUFFERED=1
      - RSU_ID=0023
    networks: 
      - network_test_bed
    command: 
      - 'python3'
      - '-u'
      - '/usr/src/app/rsu.py'

  rsu-0024:
    image: linusmotu/rsu-base:1.0
    restart: on-failure
    volumes:
      - ./rsu:/usr/src/app:z
      - ./common/:/usr/src/app/common:z
    environment:
      - PYTHONUNBUFFERED=1
      - RSU_ID=0024
    networks: 
      - network_test_bed
    command: 
      - 'python3'
      - '-u'
      - '/usr/src/app/rsu.py'

networks:
  network_test_bed:
    name: network_test_bed
    external: true